### ISSUE TITLE
Contributors fetch error

### ISSUE THREAD

**Issue by jimmyleray** [jimmyleray/Emendare#119]
**Describe the bug**
On server, Github error when try to fetch contributors list.

**To Reproduce**
Sometimes randomly on contributors fetch.

**Comment by gwenker** [comment]
One identified error is when you refresh many time the page 

```
url:
      'https://github.com/jimmyleray/Emendare/graphs/contributors-data.json',
     status: 429,
     statusText: 'Too Many Requests',
     headers: Headers { [Symbol(map)]: [Object] } } }
FetchError: invalid json response body at https://github.com/jimmyleray/Emendare/graphs/contributors-data.json reason: Unexpected token < in JSON at position 0
[..]
```

I think this error is not the same at first try but i'm not identify this yet

**Comment by gwenker** [comment]
Now i have the second parse error, it is a 202 response with no body :
```
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]:
   { body:
      PassThrough {
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: true,
        _transformState: [Object] },
     disturbed: false,
     error: null },
  [Symbol(Response internals)]:
   { url:
      'https://github.com/jimmyleray/Emendare/graphs/contributors-data.json',
     status: 202,
     statusText: 'Accepted',
     headers: Headers { [Symbol(map)]: [Object] } } }
{ FetchError: invalid json response body at https://github.com/jimmyleray/Emendare/graphs/contributors-data.json reason: Unexpected end of JSON input
    at F:\Dev\Emendare\server\node_modules\node-fetch\lib\index.js:241:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://github.com/jimmyleray/Emendare/graphs/contributors-data.json reason: Unexpected end of JSON input',
  type: 'invalid-json' }
```

**Comment by gwenker** [comment]
I will change the GET of static json by a call to github api :
https://developer.github.com/v3/repos/#list-contributors
